WIKIMEDIA_PROJECTS = [
    {
        "name": "Wikipedia",
        "mark": "W",
        "category": "Reference",
        "description": "A free, collaborative encyclopedia written in over 300 languages.",
        "url": "https://www.wikipedia.org/",
        "status": "active",
        "accent": "#202122",
    },
    {
        "name": "Wikibooks",
        "mark": "B",
        "category": "Reference",
        "description": "Free textbooks, annotated texts, instructional guides, and manuals.",
        "url": "https://www.wikibooks.org/",
        "status": "active",
        "accent": "#2f6f9f",
    },
    {
        "name": "Wiktionary",
        "mark": "T",
        "category": "Reference",
        "description": "A multilingual dictionary describing words from every language.",
        "url": "https://www.wiktionary.org/",
        "status": "active",
        "accent": "#b8561b",
    },
    {
        "name": "Wikiquote",
        "mark": "Q",
        "category": "Reference",
        "description": "A sourced collection of quotations, proverbs, mnemonics, and slogans.",
        "url": "https://www.wikiquote.org/",
        "status": "active",
        "accent": "#36677d",
    },
    {
        "name": "Wikimedia Commons",
        "mark": "C",
        "category": "Collections",
        "description": "A free-to-use library of images, illustrations, video, audio, and music.",
        "url": "https://commons.wikimedia.org/",
        "status": "active",
        "accent": "#10865f",
    },
    {
        "name": "Wikisource",
        "mark": "S",
        "category": "Collections",
        "description": "A library of freely licensed source texts and historical documents.",
        "url": "https://wikisource.org/",
        "status": "active",
        "accent": "#5a6f86",
    },
    {
        "name": "Wikiversity",
        "mark": "U",
        "category": "Collections",
        "description": "Open learning resources, learning projects, and collaborative research.",
        "url": "https://www.wikiversity.org/",
        "status": "active",
        "accent": "#9b2d30",
    },
    {
        "name": "Wikispecies",
        "mark": "S",
        "category": "Collections",
        "description": "A free taxonomy directory covering living and fossil species.",
        "url": "https://species.wikimedia.org/",
        "status": "active",
        "accent": "#547f63",
    },
    {
        "name": "Wikidata",
        "mark": "D",
        "category": "Technology",
        "description": "Collaboratively edited structured data used across Wikimedia projects.",
        "url": "https://www.wikidata.org/",
        "status": "active",
        "accent": "#285b99",
    },
    {
        "name": "Wikifunctions",
        "mark": "F",
        "category": "Technology",
        "description": "A multilingual library of code functions that anyone can edit.",
        "url": "https://www.wikifunctions.org/",
        "status": "active",
        "accent": "#8b4bb4",
    },
    {
        "name": "MediaWiki",
        "mark": "M",
        "category": "Technology",
        "description": "The free and open-source software platform behind Wikimedia projects.",
        "url": "https://www.mediawiki.org/",
        "status": "active",
        "accent": "#3d7f62",
    },
    {
        "name": "Wikivoyage",
        "mark": "V",
        "category": "Guides",
        "description": "A free, complete, and up-to-date worldwide travel guide.",
        "url": "https://www.wikivoyage.org/",
        "status": "active",
        "accent": "#2c7a8c",
    },
    {
        "name": "Meta-Wiki",
        "mark": "M",
        "category": "Collaboration",
        "description": "The central hub for coordination and discussion across Wikimedia.",
        "url": "https://meta.wikimedia.org/",
        "status": "active",
        "accent": "#6b4b8a",
    },
    {
        "name": "Wikinews",
        "mark": "N",
        "category": "Archive",
        "description": "The former collaborative news project, now preserved in read-only mode.",
        "url": "https://www.wikinews.org/",
        "status": "archived",
        "accent": "#777777",
    },
]


def get_wikimedia_projects() -> list[dict]:
    """Return the curated Wikimedia project-family catalog in display order."""
    return WIKIMEDIA_PROJECTS
